[project]
name = "sender_policy_flattener"
version = "0.5.0"
description = "Condense SPF records to network blocks to avoid DNS Lookup Limits"
authors = [{ name = "Vasili Syrakis", email = "cetanu@gmail.com" }]
requires-python = ">=3.10.0,<4"
readme = "README.md"
license = "MIT"
keywords = [
    "spf",
    "dns",
    "sender policy framework",
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Internet :: Name Service (DNS)",
    "Topic :: System :: Systems Administration",
    "Topic :: Utilities",
    "Intended Audience :: System Administrators",
    "Natural Language :: English",
]
dependencies = [
    "dnspython>=2.6",
    "netaddr>=1.0",
    "typer",
    "pydantic[email]",
    "structlog",
    "tenacity",
    "tomli; python_version < '3.11'",
]

[project.urls]
Repository = "https://github.com/cetanu/sender_policy_flattener"

[project.scripts]
spflat = "sender_policy_flattener.cli:app"

[dependency-groups]
dev = [
    "pytest",
    "pytest-spec",
    "pytest-asyncio",
    "ruff",
    "mypy",
    "types-netaddr",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
